export const imgUploadForm = document.querySelector('.img-upload__form');
export const imgUploadInput = document.querySelector('.img-upload__input');
export const imgUploadOverlay = document.querySelector('.img-upload__overlay');
export const imgUploadButtonCancel = document.querySelector('.img-upload__cancel');
export const hashtagsInput = document.querySelector('.text__hashtags');
export const descriptionInput = document.querySelector('.text__description');
export const submitButton = imgUploadForm.querySelector('.img-upload__submit');
export const scaleSmallerButton = document.querySelector('.scale__control--smaller');
export const scaleBiggerButton = document.querySelector('.scale__control--bigger');
export const scaleControlValue = document.querySelector('.scale__control--value');
export const imgUploadPreview = document.querySelector('.img-upload__preview');
export const effectLevelSlider = document.querySelector('.effect-level__slider');
export const effectLevelValue = document.querySelector('.effect-level__value');
export const imagePreview = document.querySelector('.img-upload__preview img');
export const effectLevelContainer = document.querySelector('.img-upload__effect-level');
export const effectRadios = document.querySelectorAll('input[name="effect"]');
